call = "ON3URE-4"
aprs_host = "belgium.aprs2.net"
aprs_port = 14580
passcode = "23996"  # https://apps.magicbug.co.uk/passcode/index.php/passcode
latitude = 51.1517227
longitude = 2.7649157
altitude = 46  # in meters
comment = "https://rf.guru LoraAPRSiGate v0.1"
symbol = "La"
timeout = 900  # time to wait for an APRS packet higher
msgDistance = 300  # distance in km's from source of messages
biast = False
